$kind: http-example
request:
  url: "{{AUTH_URL}}/roles/:id"
  method: DELETE
  headers:
    Content-Type: application/json
    Authorization: Bearer {{ACCESS_TOKEN}}
  pathVariables:
    id: ""
response:
  statusCode: 409
  statusText: Conflict
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "code": "CONFLICT",
        "message": "Cannot delete role: users still assigned"
      }
order: 5000
