$kind: http-example
request:
  url: "{{AUTH_URL}}/roles"
  method: POST
  headers:
    Content-Type: application/json
    Authorization: Bearer {{ACCESS_TOKEN}}
  body:
    type: json
    content: |-
      {
        "id": "example",
        "name": "example",
        "permissions": ["example"]
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "id": "head_coach",
        "name": "Head Coach",
        "permissions": ["roster:read", "roster:write", "attendance:read", "attendance:write", "payments:read", "users:read"]
      }
order: 1000
