$kind: http-request
description: Get role by id
url: "{{AUTH_URL}}/roles/:id"
method: GET
pathVariables:
  id: ""
auth:
  type: bearer
  credentials:
    token: "{{ACCESS_TOKEN}}"
examples: ./.resources/Get Role.resources/examples
order: 3000
