$kind: http-example
request:
  url: "{{AUTH_URL}}/roles"
  method: POST
  headers:
    Content-Type: application/json
    Authorization: Bearer {{ACCESS_TOKEN}}
  body:
    type: json
    content: |-
      {
        "id": "example",
        "name": "example",
        "permissions": ["example"]
      }
response:
  statusCode: 409
  statusText: Conflict
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "code": "CONFLICT",
        "message": "Role id already exists"
      }
order: 4000
