$kind: http-example
request:
  url: "{{AUTH_URL}}/roles/:id"
  method: GET
  headers:
    Authorization: Bearer {{ACCESS_TOKEN}}
  pathVariables:
    id: ""
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "id": "head_coach",
        "name": "Head Coach",
        "permissions": ["roster:read", "roster:write", "attendance:read", "attendance:write", "payments:read", "users:read"]
      }
order: 1000
